In [118]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [119]:
import load_data
import preprocess_data
import calculate as calc

In [120]:
%%time
a = load_data.binance_data('BTC/USDT', 1, '2023-03-01T00:00:00Z')

Wall time: 2min 14s

In [142]:
data = load_data.local_data('C:/Users/tempf/Desktop/algo_trader/data/BTC-USDT_binance.csv',output_dataframe=True)
data

,close,close_pct_change,5_min_EMA,15_min_EMA,25_min_EMA,35_min_EMA,45_min_EMA,55_min_EMA,200_min_EMA,RSI
0,23170.13,-0.000342,23181.324127,23180.711120,23176.637276,23174.150795,23172.604804,23171.571854,23168.034328,52.761341
1,23183.75,0.000588,23182.132754,23181.097130,23177.234343,23174.793318,23173.252700,23172.215128,23168.620980,55.207005
2,23192.95,0.000397,23185.738511,23182.599684,23178.544373,23175.994962,23174.381212,23173.291964,23169.504957,55.889494
3,23199.66,0.000289,23190.379015,23184.758556,23180.293280,23177.544692,23175.809769,23174.639494,23170.572454,58.509198
4,23200.05,0.000017,23193.602680,23186.690607,23181.920035,23179.003984,23177.162009,23175.918407,23171.590069,56.695204
...,...,...,...,...,...,...,...,...,...,...
54055,27928.41,0.000240,27923.489337,27921.943798,27922.157826,27922.611839,27922.874674,27922.823915,27912.656087,66.007009
54056,27928.41,0.000000,27925.129558,27922.752074,27922.638762,27922.933959,27923.115340,27923.023418,27912.812843,55.920877
54057,27933.23,0.000173,27927.829705,27924.061814,27923.453473,27923.505961,27923.555108,27923.387939,27913.015998,60.951930
54058,27923.08,-0.000363,27926.246470,27923.939088,27923.424744,27923.482297,27923.534451,27923.376941,27913.116138,45.308971
54059,27918.12,-0.000178,27923.537647,27923.211702,27923.016687,27923.184391,27923.299040,27923.189193,27913.165927,46.453378